export const FIRST_NUM = "FIRST_NUM"
export const SECOND_NUM = "SECOND_NUM"
export const OPERATOR = "OPERATOR"

export const ZERO = "ZERO"
export const ONE = "ONE"
export const TWO = "TWO"
export const THREE = "THREE"
export const FOUR = "FOUR"
export const FIVE = "FIVE"
export const SIX = "SIX"
export const SEVEN = "SEVEN"
export const EIGHT = "EIGHT"
export const NINE = "NINE"

export const ADD = "ADD"
export const SUB = "SUB"
export const MUL = "MUL"
export const DIV = "DIV"
export const MOD = "MOD"

export const EQUAL = "EQUAL"
export const ANS = "ANS"
export const CE = "CE"